export const FETCH_PRODUCTS_START = "FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";

export const CONTENTS_START = "CONTENTS_START";
export const CONTENTS_SUCCESS = "CONTENTS_SUCCESS";
export const CONTENTS_DELETE = "CONTENTS_DELETE";
export const CONTENTS_FAIL = "CONTENTS_FAIL";
